arrowParens: always
bracketSameLine: false
bracketSpacing: false
embeddedLanguageFormatting: 'auto'
htmlWhitespaceSensitivity: 'css'
insertPragma: false
jsxSingleQuote: false
proseWrap: 'preserve'
quoteProps: 'as-needed'
printWidth: 100
requirePragma: false
semi: true
singleQuote: true
trailingComma: 'all'
tabWidth: 2
useTabs: false
vueIndentScriptAndStyle: false
